spring.datasource.url=jdbc:postgresql://localhost:5432/aidir
spring.datasource.username=aidir
spring.datasource.password=aidir
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
server.port=8222

#JANK
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

#spring.security.user.name=bow
#spring.security.user.password=arrow

# drupal
drupal.url=http://127.0.0.1:62371
drupal.user=admin
drupal.password=admin

# strapi
strapi.api.url=http://127.0.0.1:1337
strapi.api.token=6e137b5eb36eb64cf2baa6c17149493d315e70b81c5e5af47bb2cf7033b2c82ae5cb93eeef3a1a63f7ef6e45cc42c3393eb277a4e0b31f7c21b0d1bfc09a2d4f398187337e509e19bf1bde2dc127b06b124b8dc5aec8415b2d855e957e4d079e04a3bd681f0dcdd551f34636b732b7a8dee1f2c021dddf021816016970b82236

# directus
directus.api.url=http://127.0.0.1:8055
directus.api.token=aWSZHR0GnEJxyxjemBjRpQle-Vz3yGC2

# liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog.xml
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
