--liquibase formatted sql
--changeset liquibase-radu:1

CREATE TABLE role
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) UNIQUE NOT NULL,
    description VARCHAR
);

CREATE TABLE permission
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) UNIQUE NOT NULL,
    description VARCHAR
);

CREATE TABLE role_permission
(
    role BIGINT REFERENCES role (id) ON DELETE CASCADE,
    permission BIGINT REFERENCES permission (id) ON DELETE CASCADE,
    CONSTRAINT roles_permission_unique UNIQUE (role, permission)
);

CREATE TABLE data_permission
(
   permission_name VARCHAR REFERENCES permission (name) ON DELETE CASCADE,
   data_key VARCHAR NOT NULL,
   scope VARCHAR NOT NULL,
   CONSTRAINT data_permission_unique UNIQUE(permission_name, data_key)
);

CREATE TABLE account_types (
    name VARCHAR NOT NULL UNIQUE
);

INSERT INTO account_types (name) VALUES ('vendor'), ('talent');

CREATE TABLE account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR NOT NULL, -- hashed by the application, nothing here enforces that
    account_type VARCHAR NOT NULL REFERENCES account_types(name),
    role BIGINT REFERENCES role (id) ON DELETE CASCADE,
    terms_accepted_at TIMESTAMPTZ -- the onboarding "I agree" checkbox, kept as when rather than whether
);

CREATE TABLE plan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_type VARCHAR NOT NULL REFERENCES account_types(name), -- a vendor 'free' is not a talent 'free'
    name VARCHAR NOT NULL,
    CONSTRAINT plan_name_per_account_type UNIQUE (account_type, name)
);

INSERT INTO plan (account_type, name) VALUES
    ('vendor','free'),('vendor','verified'),('vendor','growth'),('vendor','premium'),
    ('talent','free'),('talent','verified'),('talent','pro'),('talent','marketplace');

CREATE TABLE plan_addon (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL
    -- might want recurrence to live here as well
);

-- need to handle upgrades, subscription history
CREATE TABLE subscription (
    account_id BIGINT REFERENCES account(id),
    plan_id BIGINT REFERENCES plan(id),
    period_start TIMESTAMPTZ NOT NULL default NOW(),
    period_end TIMESTAMPTZ NOT NULL default NOW() + INTERVAL '1 year',
    active BOOLEAN default true
);

-- some of the addons are one-off things (re-verification),
-- others are ongoing, or valid for a certain number of events (vendor promos, newsletter etc.)
-- todo: this will certainly need review once we start testing the add-on flow
CREATE TABLE subscription_addon (
    account_id BIGINT REFERENCES account(id),
    plan_addon_id BIGINT REFERENCES plan_addon(id),
    added TIMESTAMPTZ NOT NULL default NOW(),
    active BOOLEAN default true
);

CREATE TABLE company_information (
    account_id BIGINT REFERENCES account(id),
    official_name VARCHAR NOT NULL,
    website_url VARCHAR NOT NULL,
    description VARCHAR NOT NULL
);

CREATE TABLE pricing (
    type VARCHAR NOT NULL UNIQUE
);

INSERT INTO pricing (type) VALUES
    ('free'),('freemium'),('paid');

CREATE TABLE category (
    name VARCHAR PRIMARY KEY
);

-- Reference vocabularies. These are seeded from what the front end currently hardcodes, and are meant to
-- become the source for those pickers rather than the other way round: SKILL_OPTIONS and LANGUAGE_OPTIONS
-- in src/components/user-onboarding/constants.ts, and the location field that is still free text.
CREATE TABLE skill (
    name VARCHAR PRIMARY KEY
);

INSERT INTO skill (name) VALUES
    ('Agents'),('Airflow'),('Analytics'),('Architecture'),('Audio'),('AWS'),('Azure'),('C++'),
    ('Chatbot'),('ChatGPT'),('Computer Vision'),('Conversation Design'),('Copywriting'),('CUDA'),
    ('dbt'),('Deep Learning'),('Discovery'),('Distillation'),('Evaluation'),('Figma'),('Forecasting'),
    ('Generative AI'),('Governance'),('Healthcare AI'),('Hiring'),('Interviews'),('JAX'),('Kubernetes'),
    ('LangChain'),('Leadership'),('LLM'),('MLOps'),('NLP'),('Observability'),('OpenAI'),('Policy'),
    ('Postgres'),('Product Strategy'),('Python'),('PyTorch'),('RAG'),('Ranking'),('Recommenders'),
    ('Risk'),('Robotics'),('scikit-learn'),('Security'),('Spark'),('Speech Recognition'),('SQL'),
    ('Statistics'),('Strategy'),('TensorRT'),('Terraform'),('Transformers'),('TypeScript'),
    ('UX Research'),('Validation'),('vLLM'),('Workshops');

CREATE TABLE language (
    name VARCHAR PRIMARY KEY
);

INSERT INTO language (name) VALUES
    ('Arabic'),('Danish'),('Dutch'),('English'),('French'),('German'),('Hindi'),('Italian'),
    ('Japanese'),('Mandarin Chinese'),('Polish'),('Portuguese'),('Romanian'),('Russian'),('Spanish'),
    ('Swahili'),('Swedish'),('Tamil'),('Turkish');

CREATE TABLE location (
    name VARCHAR PRIMARY KEY -- "City, Country", the form the front end already displays
);

INSERT INTO location (name) VALUES
    ('Amsterdam, Netherlands'),('Austin, United States'),('Bangalore, India'),('Barcelona, Spain'),
    ('Berlin, Germany'),('Bogotá, Colombia'),('Copenhagen, Denmark'),('Dubai, United Arab Emirates'),
    ('Istanbul, Türkiye'),('Lagos, Nigeria'),('Lisbon, Portugal'),('London, United Kingdom'),
    ('Milan, Italy'),('Montreal, Canada'),('Munich, Germany'),('Nairobi, Kenya'),('Paris, France'),
    ('São Paulo, Brazil'),('Singapore'),('Stockholm, Sweden'),('Tokyo, Japan'),('Toronto, Canada'),
    ('Vienna, Austria'),('Warsaw, Poland');

CREATE TABLE tool_submission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL, -- setting these two as unique creates opportunities for denial-of-service / prevents resubmission if rejected for fixable reason
    url VARCHAR(250) NOT NULL, -- ---
    pricing VARCHAR NOT NULL REFERENCES pricing(type),
    short_description VARCHAR(250) NOT NULL,
    long_description VARCHAR,
    tags JSONB,
    categories JSONB,
    features JSONB,
    plans JSONB,
    free_tier_plan_id VARCHAR,
    highlight_plan_id VARCHAR,
    integrations JSONB,
    demo_video_url VARCHAR,
    submitted_by VARCHAR(500) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL default NOW(),
    approved_at TIMESTAMPTZ,
    approved BOOLEAN,
    uploaded_to_cms BOOLEAN default false
);

CREATE TABLE tool_submission_category (
    tool_submission_id BIGINT NOT NULL REFERENCES tool_submission(id),
    category VARCHAR NOT NULL REFERENCES category(name),
    CONSTRAINT tool_submission_category_unique UNIQUE(tool_submission_id, category)
);

CREATE TABLE tool_submission_image_metadata (
    tool_submission_id BIGINT NOT NULL REFERENCES tool_submission(id),
    image_path VARCHAR,
    CONSTRAINT tool_submission_image_metadata_unique UNIQUE(tool_submission_id, image_path)
);

-- Talent onboarding. Unlike a tool submission there is no approval queue: the wizard creates the account
-- and its profile outright, so this is normalised rather than parked in JSONB - the talent directory
-- filters on skills, workplace, location, employment type and languages.
CREATE TABLE talent_profile (
    account_id BIGINT PRIMARY KEY REFERENCES account(id),
    full_name VARCHAR(200) NOT NULL,
    country VARCHAR NOT NULL, -- todo: reference table, the front end already ships a fixed COUNTRIES list
    title VARCHAR(200) NOT NULL,
    short_description VARCHAR(180),  -- SHORT_DESCRIPTION_MAX_LENGTH
    summary VARCHAR(1000) NOT NULL,  -- SUMMARY_MAX_LENGTH
    resume_file_name VARCHAR,
    work_location VARCHAR NOT NULL REFERENCES location(name),
    work_relocation VARCHAR NOT NULL,
    work_workplace VARCHAR NOT NULL,
    work_employment_type VARCHAR NOT NULL,
    link_linkedin VARCHAR,
    link_github VARCHAR,
    link_portfolio VARCHAR,
    link_other VARCHAR,
    created_at TIMESTAMPTZ NOT NULL default NOW()
);

CREATE TABLE talent_skill (
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    skill VARCHAR NOT NULL REFERENCES skill(name),
    CONSTRAINT talent_skill_unique UNIQUE (account_id, skill)
);

CREATE INDEX talent_skill_skill_idx ON talent_skill (skill);

CREATE TABLE talent_language (
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    language VARCHAR NOT NULL REFERENCES language(name),
    proficiency VARCHAR NOT NULL,
    display_order INT NOT NULL default 0,
    CONSTRAINT talent_language_unique UNIQUE (account_id, language)
);

-- display_order preserves the order the rows were entered in the wizard; the ids the form carries
-- ("exp-1", "edu-1") are React keys regenerated every session and are deliberately not stored.
CREATE TABLE talent_experience (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    display_order INT NOT NULL default 0,
    company VARCHAR NOT NULL,
    position VARCHAR NOT NULL,
    location VARCHAR REFERENCES location(name),
    workplace VARCHAR,
    period VARCHAR,
    description VARCHAR
);

CREATE TABLE talent_education (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    display_order INT NOT NULL default 0,
    institution VARCHAR NOT NULL,
    degree VARCHAR NOT NULL,
    field VARCHAR NOT NULL,
    graduation_year VARCHAR(4) NOT NULL,
    location VARCHAR NOT NULL REFERENCES location(name)
);

CREATE TABLE talent_certification (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    display_order INT NOT NULL default 0,
    name VARCHAR NOT NULL,
    organization VARCHAR NOT NULL,
    year VARCHAR(4)
);

CREATE TABLE talent_course (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    display_order INT NOT NULL default 0,
    name VARCHAR NOT NULL,
    provider VARCHAR,
    focus VARCHAR,
    completion_year VARCHAR(4)
);

CREATE TABLE talent_project (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES talent_profile(account_id),
    display_order INT NOT NULL default 0,
    title VARCHAR NOT NULL,
    category VARCHAR,
    year VARCHAR(4),
    description VARCHAR
);
