--liquibase formatted sql
--changeset liquibase-radu:1

CREATE TABLE role
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) UNIQUE NOT NULL,
    description VARCHAR
);

CREATE TABLE permission
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) UNIQUE NOT NULL,
    description VARCHAR
);

CREATE TABLE role_permission
(
    role BIGINT REFERENCES role (id) ON DELETE CASCADE,
    permission BIGINT REFERENCES permission (id) ON DELETE CASCADE,
    CONSTRAINT roles_permission_unique UNIQUE (role, permission)
);

CREATE TABLE data_permission
(
   permission_name VARCHAR REFERENCES permission (name) ON DELETE CASCADE,
   data_key VARCHAR NOT NULL,
   scope VARCHAR NOT NULL,
   CONSTRAINT data_permission_unique UNIQUE(permission_name, data_key)
);

CREATE TABLE account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role BIGINT REFERENCES role (id) ON DELETE CASCADE
);

CREATE TABLE pricing (
    type VARCHAR NOT NULL UNIQUE
);

INSERT INTO pricing (type) VALUES
    ('free'),('freemium'),('paid');

CREATE TABLE tool_submission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL, -- setting these two as unique creates opportunities for denial-of-service / prevents resubmission if rejected for fixable reason
    url VARCHAR(250) NOT NULL, -- ---
    pricing VARCHAR NOT NULL REFERENCES pricing(type),
    short_description VARCHAR(250) NOT NULL,
    long_description VARCHAR,
    category VARCHAR(50),
    tags JSONB,
    image VARCHAR,
    ratings BIGINT,
    submitted_by VARCHAR(500) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL default NOW(),
    approved_at TIMESTAMPTZ,
    approved BOOLEAN,
    uploaded_to_cms BOOLEAN default false
);
